version: "3"

services:
  # -------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django/staticfiles
      - media_volume:/home/app/django/mediafiles
    expose:
      - 8000
    env_file:
      - ./.envs/production/.django
      - ./.envs/production/.postgres
    depends_on:
      - postgresdb
  # -------------------------------------------------------
  postgresdb:
    image: postgres:alpine # I would suggest pinning this to a version
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/production/.postgres
  # -------------------------------------------------------
  nginx:
    image: nginx:alpine # I would suggest pinning this to a version
    volumes:
      - ./docker/production/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/django/staticfiles
      - media_volume:/home/app/django/mediafiles
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
