version: "3"

networks:
  default:

  nginx-proxy:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  # -------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        requirements: requirements.txt # this is the name of the requirements file you wish to be installed
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2
    volumes:
      - static_volume:/home/app/django/staticfiles
      - media_volume:/home/app/django/mediafiles
    env_file:
      - ./.envs/production/.django
      - ./.envs/production/.postgres
    depends_on:
      - postgresdb
    restart: unless-stopped
  # -------------------------------------------------------
  postgresdb:
    image: postgres:alpine # I would suggest pinning this to a version
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/production/.postgres
    restart: unless-stopped
  # -------------------------------------------------------
  nginx:
    image: nginx:alpine # I would suggest pinning this to a version
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/django/staticfiles
      - media_volume:/home/app/django/mediafiles
    env_file:
      - ./.envs/production/.nginx_proxy
    depends_on:
      - django
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy
